"failed injection into th19.exe" = "th19.exe への注入に失敗しました"
"completed injection into th19.exe" = "th19.exe への注入が完了しました"
"you can close this window by pressing enter..." = "エンターキーを押してこのウィンドウを閉じることができます..."
